---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 29856.
--- DateTime: 2024/3/29 12:10
---
if (redis.call('get',KEYS[1]) == ARGV[1]) then
    return redis.call('del',KEYS[1])
end
return 0